# Generated by Django 4.2.7 on 2023-11-03 18:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
